---
# Deploy frontend to public_html (Apache serves static files)
# Deploy API backend stays in repositories/quonote_app
deployment:
  tasks:
    - export DEPLOYPATH=/home/fjeyytqhry/public_html
    - /bin/cp -rf dist/* $DEPLOYPATH/
    - /bin/cp -f .htaccess $DEPLOYPATH/ 2>/dev/null || true
